export * from './address.type';
export * from './ward.type';
export * from './district.type';
export * from './bank.type';
export * from './cmstaff.type';
export * from './cmstore.type';
export * from './dvmethod.type';
export * from './order.type';
export * from './staff.type';
export * from './status.type';
export * from './store.type';
export * from './type-staff.type';
export * from './warehouse.type';
export type Role = 'STORE' | 'DELIVERY' | 'MANAGER';
